name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # trigger only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            # Load nvm so node and npm are available
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Go to frontend folder
            cd /home/ubuntu/devconnect-frontend

            # Pull latest code
            git pull origin main

            # Install dependencies
            npm install

            # Build React app
            npm run build

            # Copy build to Nginx folder
            sudo scp -r dist/* /var/www/html/

            # Optional: reload Nginx (if needed)
            sudo systemctl reload nginx
